# Intro to Numpy

Numpy provides efficient storage and manipulation for **numerical** arrays. Numpy arrays are like Python's built in list type. Anything can be thought of as an n-dimensional array.
* Digital Images: two dimensional arrays of numbers representing pixel brightness across area.
* Sound clips: one dimensional arrays of intensity vs time.


In [1]:
import numpy as np

## Creating Numpy Arrays from Scratch
Using routines built into numpy is a quick and efficient way to build arrays.

In [2]:
# Create an array filled with zeroes
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [3]:
# Create a nxn matrices of only ones
n = 3
np.ones((n,n), dtype=float)

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [4]:
# Create 3x5 matrix with a parameter(s)
x = 5
np.full((3,5), x)

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [5]:
# Create array of n values evenly spaced between 0 and 1
n = 5
np.linspace(0, 1, n)

array([ 0.  ,  0.25,  0.5 ,  0.75,  1.  ])

In [6]:
# Create nxn matrix of uniformly distributed random values between 0,1
n = 3
np.random.random((n,n))

array([[ 0.93940507,  0.57055585,  0.71270686],
       [ 0.08960468,  0.31543322,  0.64030527],
       [ 0.12819834,  0.54316097,  0.4928076 ]])

In [7]:
# Create a 3x3 array of random intergers in range [0,10]
np.random.randint(0, 10, (3,3))

array([[5, 5, 9],
       [4, 3, 1],
       [8, 8, 5]])

In [8]:
# Create a nxn identity matrix
n=5
np.eye(n, dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

## Numpy Array Attributes
Before we discuss numpy array attributes we will define three arrays from one to three dimensions.

In [9]:
np.random.seed(0) #seed the rng

x1 = np.random.randint(10, size=6) # One dimensional array size 6
x2 = np.random.randint(10, size=(3,4)) # Two-dimensional
x3 = np.random.randint(10, size=(3,4,5)) # Three-dimensional

Each numpy array has the following attributes
  * ndim: Number of dimensions
  * shape: Size of each dimension
  * size: total size of array
  * dtype: data type of the array
      * remember that numpy arrays have uniform data types
  * Byte size:
      * itemsize: size (in bytes) of each array element
      * nbytes: total size (in bytes) of the array
     

In [10]:
print("x3 ndim: ", x3.ndim)
print("x3 shape: ", x3.shape)
print("x3 size: ", x3.size)
print("x3 dtype: ", x3.dtype)
print("x3 itemsize: ", x3.itemsize)
print("x3 nbytes: ", x3.nbytes)

x3 ndim:  3
x3 shape:  (3, 4, 5)
x3 size:  60
x3 dtype:  int64
x3 itemsize:  8
x3 nbytes:  480
